### ISSUE TITLE
put ispdb on github

### ISSUE THREAD

**Issue by Sancus** [thundernest/thundernest-ansible#12]
https://svn.mozilla.org/mozillamessaging.com/sites/ispdb.mozillamessaging.com/ should go on github for archival purposes

**Comment by benbucksch** [comment]
that's the scripts, including the one in #11

**Comment by Sancus** [comment]
https://github.com/mozilla/ispdb I forgot that we actually did that years ago, and had a student working on it for a while.

So the SVN repo is actually out of date. Although nothing significant about https://github.com/mozilla/ispdb/blob/master/tools/convert.py was changed.

**Comment by clokep** [comment]
By "put this on GitHub" do you mean the web frontend or the data itself?

**Comment by Sancus** [comment]
This bug was about the old web front-end and its associated scripts. The data is already on github @ https://github.com/thundernest/autoconfig (and well, turns out the old front-end was as well) so there was really nothing to do for this issue :)

**Comment by benbucksch** [comment]
> This ... was... the old web front-end and its associated scripts

Sancus, correct.

This thing here was never production-ready.
