### ISSUE TITLE
move ispdb convert.py to git

### ISSUE THREAD

**Issue by Sancus** [thundernest/thundernest-ansible#22]
https://svn.mozilla.org/mozillamessaging.com/sites/ispdb.mozillamessaging.com/trunk/tools/convert.py

**Comment by benbucksch** [comment]
The other tools (esp. quickparse), too, please.

Thanks! :)

**Comment by benbucksch** [comment]
already done :)
https://github.com/mozilla/ispdb/tree/master/tools
